# general
seed: 1
device: 'cuda'
output_path: 'results/deer1'

# data
image_path: 'data/deer1.jpg'
latents_path: 'latents_forward'


# diffusion
sd_version: '2.1'
guidance_scale: 10.5
n_timesteps: 50

prompt: ''

prompt_gene: 'painting of <sss>, deer, grass; painting of <sss>, deer, grass'
lora_name: 'lora_deer_c1; lora_deer_c2'
mask: 'deer1_grass; deer1_deer'

negative_prompt: ugly, blurry, black, low res, unrealistic

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
